<a href="https://colab.research.google.com/github/LucasSFlores80/Data-Science-I/blob/main/An%C3%A1lisis_de_Riesgos_de_muerte_respecto_a_diferentes_factores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
url = 'https://raw.githubusercontent.com/LucasSFlores80/Data-Science-I/main/number-of-deaths-by-risk-factor.csv'
data_2 = pd.read_csv(url, index_col=0)
data_2

,Code,Year,Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Secondhand smoke - Sex: Both - Age: All Ages (Number),...,Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)
Entity,,,,,,,,,,,,,,,,,,,,,
Afghanistan,AFG,1990,3169,25633,1045,7077,356,3185,3702,4794,...,9518,2798,4825,174,389,2016,7686,107,2216,564
Afghanistan,AFG,1991,3222,25872,1055,7149,364,3248,4309,4921,...,9489,3254,5127,188,389,2056,7886,121,2501,611
Afghanistan,AFG,1992,3395,26309,1075,7297,376,3351,5356,5279,...,9528,4042,5889,211,393,2100,8568,150,3053,700
Afghanistan,AFG,1993,3623,26961,1103,7499,389,3480,7152,5734,...,9611,5392,7007,232,411,2316,9875,204,3726,773
Afghanistan,AFG,1994,3788,27658,1134,7698,399,3610,7192,6050,...,9675,5418,7421,247,413,2665,11031,204,3833,812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zimbabwe,ZWE,2015,2835,11483,1063,1354,4854,1820,4336,1614,...,5636,2879,4328,1068,407,138,730,21,734,282
Zimbabwe,ZWE,2016,2781,11663,1082,1383,4915,1854,4244,1625,...,5849,2798,4295,1042,415,101,674,20,700,275
Zimbabwe,ZWE,2017,2700,11819,1098,1409,4992,1883,4193,1625,...,6047,2744,4251,1007,424,82,629,19,678,267
Zimbabwe,ZWE,2018,2669,12002,1117,1439,5044,1917,4013,1628,...,6248,2608,4153,969,434,85,607,17,644,261
Zimbabwe,ZWE,2019,2680,12241,1140,1475,5156,1960,3914,1646,...,6475,2531,4113,963,438,81,585,16,631,259

In [4]:
# Analizo la información de las columnas. Los nombres de las variables y de que tipo de dato se trata
data_2 .info()

<class 'pandas.core.frame.DataFrame'>
Index: 6840 entries, Afghanistan to Zimbabwe
Data columns (total 30 columns):
 #   Column                                                                                                            Non-Null Count  Dtype
---  ------                                                                                                            --------------  -----
 0   Code                                                                                                              6150 non-null   object
 1   Year                                                                                                              6840 non-null   int64
 2   Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number)              6840 non-null   int64
 3   Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number)              6840 non-null   int64
 4   Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number)                       6840 non-null   int64
 5   Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number)                  6840 non-null   int64
 6   Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number)                               6840 non-null   int64
 7   Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number)                        6840 non-null   int64
 8   Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number)                       6840 non-null   int64
 9   Deaths - Cause: All causes - Risk: Secondhand smoke - Sex: Both - Age: All Ages (Number)                          6840 non-null   int64
 10  Deaths - Cause: All causes - Risk: Low birth weight - Sex: Both - Age: All Ages (Number)                          6840 non-null   int64
 11  Deaths - Cause: All causes - Risk: Child wasting - Sex: Both - Age: All Ages (Number)                             6840 non-null   int64
 12  Deaths - Cause: All causes - Risk: Unsafe sex - Sex: Both - Age: All Ages (Number)                                6840 non-null   int64
 13  Deaths - Cause: All causes - Risk: Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number)                6840 non-null   int64
 14  Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number)  6840 non-null   int64
 15  Deaths - Cause: All causes - Risk: Diet low in vegetables - Sex: Both - Age: All Ages (Number)                    6840 non-null   int64
 16  Deaths - Cause: All causes - Risk: Low physical activity - Sex: Both - Age: All Ages (Number)                     6840 non-null   int64
 17  Deaths - Cause: All causes - Risk: Smoking - Sex: Both - Age: All Ages (Number)                                   6840 non-null   int64
 18  Deaths - Cause: All causes - Risk: High fasting plasma glucose - Sex: Both - Age: All Ages (Number)               6840 non-null   int64
 19  Deaths - Cause: All causes - Risk: Air pollution - Sex: Both - Age: All Ages (Number)                             6840 non-null   int64
 20  Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number)                      6840 non-null   int64
 21  Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number)                         6840 non-null   int64
 22  Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number)         6840 non-null   int64
 23  Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number)                                  6840 non-null   int64
 24  Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number)                  6840 non-null   int64
 25  Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number)                      6840 non-null   int64
 26  Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number)                            6840 non-null   int64
 27  Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number)                6840 non-null   int64
 28  Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number)               6840 non-null   int64
 29  Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)                           6840 non-null   int64
dtypes: int64(29), object(1)
memory usage: 1.6+ MB

Sería recomendable cambiar el índice de las columnas ya que se trata de nombres extensos. Para ello se establece:

0 = COD (Código)

1 = AÑO (Año)

2 = CAE (Contaminación aire exterior)

3 = HIP (Hipertensión)

4 = DAS (Dieta alta en sodio)

5 = DBG (Dieta baja en granos)

6 = ALC (Alcoholismo)

7 = DBF (Dieta baja en frutas)

8 = AGI (Agua insalubre)

9 = FUP (Fumador pasivo)

10 = BPN (Bajo peso al nacer)

11 = DEI (Desnutrición infantil)

12 = SXI (Sexo inseguro)

13 = DBS (Dieta baja en semillas)

14 = ACC (Aire contaminado por combustibles)

15 = DBV (Dieta baja en vegetales)

16 = BAF (Baja actividad física)

17 = TAB (Tabaquismo)

18 = GLU (Glucemia alta)

19 = CAI (Contaminación del aire)

20 = IMC (IMC alto)

21 = FSA (Falta de sanitarios)

22 = FLA (Falta de lavabos)

23 = DRO (Drogadicción)

24 = BDO (Baja densidad ósea)

25 = AVI (Avitaminosis)

26 = REC (Retraso en crecimiento)

27 = LMD (Lactancia materna discontinuada)

28 = LMN (Lactancia materna no exclusiva)

29 = DFE (Deficiencia de hierro)

In [5]:
# Cambio los índices de las columnas
data_2_v1 = data_2.rename(columns={"Code":"COD", "Year":"AÑO","Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number)":"CAE","Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number)":"HIP","Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number)":"DAS","Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number)":"DBG","Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number)":"ALC","Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number)":"DBF","Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number)":"AGI","Deaths - Cause: All causes - Risk: Secondhand smoke - Sex: Both - Age: All Ages (Number)":"FUP","Deaths - Cause: All causes - Risk: Low birth weight - Sex: Both - Age: All Ages (Number)":"BPN","Deaths - Cause: All causes - Risk: Child wasting - Sex: Both - Age: All Ages (Number)":"DEI","Deaths - Cause: All causes - Risk: Unsafe sex - Sex: Both - Age: All Ages (Number)":"SXI","Deaths - Cause: All causes - Risk: Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number)":"DBS","Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number)":"ACC","Deaths - Cause: All causes - Risk: Diet low in vegetables - Sex: Both - Age: All Ages (Number)":"DBV","Deaths - Cause: All causes - Risk: Low physical activity - Sex: Both - Age: All Ages (Number)":"BAF","Deaths - Cause: All causes - Risk: Smoking - Sex: Both - Age: All Ages (Number)":"TAB","Deaths - Cause: All causes - Risk: High fasting plasma glucose - Sex: Both - Age: All Ages (Number)":"GLU","Deaths - Cause: All causes - Risk: Air pollution - Sex: Both - Age: All Ages (Number)":"CAI","Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number)":"IMC","Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number)":"FSA","Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number)":"FLA","Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number)":"DRO","Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number)":"BDO","Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number)":"AVI","Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number)":"REC","Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number)":"LMD","Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number)":"LMN","Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)":"DFE"})

In [6]:
# Observamos si las columnas cambiaron
data_2_v1

,COD,AÑO,CAE,HIP,DAS,DBG,ALC,DBF,AGI,FUP,...,IMC,FSA,FLA,DRO,BDO,AVI,REC,LMD,LMN,DFE
Entity,,,,,,,,,,,,,,,,,,,,,
Afghanistan,AFG,1990,3169,25633,1045,7077,356,3185,3702,4794,...,9518,2798,4825,174,389,2016,7686,107,2216,564
Afghanistan,AFG,1991,3222,25872,1055,7149,364,3248,4309,4921,...,9489,3254,5127,188,389,2056,7886,121,2501,611
Afghanistan,AFG,1992,3395,26309,1075,7297,376,3351,5356,5279,...,9528,4042,5889,211,393,2100,8568,150,3053,700
Afghanistan,AFG,1993,3623,26961,1103,7499,389,3480,7152,5734,...,9611,5392,7007,232,411,2316,9875,204,3726,773
Afghanistan,AFG,1994,3788,27658,1134,7698,399,3610,7192,6050,...,9675,5418,7421,247,413,2665,11031,204,3833,812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zimbabwe,ZWE,2015,2835,11483,1063,1354,4854,1820,4336,1614,...,5636,2879,4328,1068,407,138,730,21,734,282
Zimbabwe,ZWE,2016,2781,11663,1082,1383,4915,1854,4244,1625,...,5849,2798,4295,1042,415,101,674,20,700,275
Zimbabwe,ZWE,2017,2700,11819,1098,1409,4992,1883,4193,1625,...,6047,2744,4251,1007,424,82,629,19,678,267
Zimbabwe,ZWE,2018,2669,12002,1117,1439,5044,1917,4013,1628,...,6248,2608,4153,969,434,85,607,17,644,261
Zimbabwe,ZWE,2019,2680,12241,1140,1475,5156,1960,3914,1646,...,6475,2531,4113,963,438,81,585,16,631,259

In [7]:
# Veo los datos nulos
data_2_v1.isnull().sum().sum()

690

In [8]:
# Son 690, vemos en que columnas están
data_2_v1.isnull().sum()

COD    690
AÑO      0
CAE      0
HIP      0
DAS      0
DBG      0
ALC      0
DBF      0
AGI      0
FUP      0
BPN      0
DEI      0
SXI      0
DBS      0
ACC      0
DBV      0
BAF      0
TAB      0
GLU      0
CAI      0
IMC      0
FSA      0
FLA      0
DRO      0
BDO      0
AVI      0
REC      0
LMD      0
LMN      0
DFE      0
dtype: int64

In [9]:
# Todos los datos faltantes pertenecen al código de país. ¿Cuáles serán los países?
# Cambiamos los NaN por 1
data_2_v2 = data_2_v1.fillna(1)
# Consultamos dentro de la columna COD el valor 1 para saber que países o zonas son. Se filtra por año para que muestre solamente una vez el país o zona
data_2_v3 = data_2_v2[(data_2_v2['COD']==1) & (data_2_v2['AÑO']==1990)]
data_2_v3['COD']

Entity
African Region (WHO)                  1
East Asia & Pacific (WB)              1
Eastern Mediterranean Region (WHO)    1
England                               1
Europe & Central Asia (WB)            1
European Region (WHO)                 1
G20                                   1
Latin America & Caribbean (WB)        1
Middle East & North Africa (WB)       1
North America (WB)                    1
Northern Ireland                      1
OECD Countries                        1
Region of the Americas (WHO)          1
Scotland                              1
South Asia (WB)                       1
South-East Asia Region (WHO)          1
Sub-Saharan Africa (WB)               1
Wales                                 1
Western Pacific Region (WHO)          1
World Bank High Income                1
World Bank Low Income                 1
World Bank Lower Middle Income        1
World Bank Upper Middle Income        1
Name: COD, dtype: object

In [10]:
# Son 23 países o zonas que tienen originalmente el COD el valor NaN
data_2_v2.loc[data_2_v2["COD"] == "African Region (WHO)", ] = 0

IndexError: tuple index out of range