<a href="https://colab.research.google.com/github/LucasSFlores80/Data-Science-I/blob/main/An%C3%A1lisis_de_Riesgos_de_muerte_respecto_a_diferentes_factores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [14]:
url = 'https://raw.githubusercontent.com/LucasSFlores80/Data-Science-I/main/number-of-deaths-by-risk-factor.csv'
data_2 = pd.read_csv(url)
data_2

,Entity,Code,Year,Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number),...,Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)
0,Afghanistan,AFG,1990,3169,25633,1045,7077,356,3185,3702,...,9518,2798,4825,174,389,2016,7686,107,2216,564
1,Afghanistan,AFG,1991,3222,25872,1055,7149,364,3248,4309,...,9489,3254,5127,188,389,2056,7886,121,2501,611
2,Afghanistan,AFG,1992,3395,26309,1075,7297,376,3351,5356,...,9528,4042,5889,211,393,2100,8568,150,3053,700
3,Afghanistan,AFG,1993,3623,26961,1103,7499,389,3480,7152,...,9611,5392,7007,232,411,2316,9875,204,3726,773
4,Afghanistan,AFG,1994,3788,27658,1134,7698,399,3610,7192,...,9675,5418,7421,247,413,2665,11031,204,3833,812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6835,Zimbabwe,ZWE,2015,2835,11483,1063,1354,4854,1820,4336,...,5636,2879,4328,1068,407,138,730,21,734,282
6836,Zimbabwe,ZWE,2016,2781,11663,1082,1383,4915,1854,4244,...,5849,2798,4295,1042,415,101,674,20,700,275
6837,Zimbabwe,ZWE,2017,2700,11819,1098,1409,4992,1883,4193,...,6047,2744,4251,1007,424,82,629,19,678,267
6838,Zimbabwe,ZWE,2018,2669,12002,1117,1439,5044,1917,4013,...,6248,2608,4153,969,434,85,607,17,644,261
6839,Zimbabwe,ZWE,2019,2680,12241,1140,1475,5156,1960,3914,...,6475,2531,4113,963,438,81,585,16,631,259

In [15]:
# Analizo la información de las columnas. Los nombres de las variables y de que tipo de dato se trata
data_2 .info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6840 entries, 0 to 6839
Data columns (total 31 columns):
 #   Column                                                                                                            Non-Null Count  Dtype
---  ------                                                                                                            --------------  -----
 0   Entity                                                                                                            6840 non-null   object
 1   Code                                                                                                              6150 non-null   object
 2   Year                                                                                                              6840 non-null   int64
 3   Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number)              6840 non-null   int64
 4   Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number)              6840 non-null   int64
 5   Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number)                       6840 non-null   int64
 6   Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number)                  6840 non-null   int64
 7   Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number)                               6840 non-null   int64
 8   Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number)                        6840 non-null   int64
 9   Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number)                       6840 non-null   int64
 10  Deaths - Cause: All causes - Risk: Secondhand smoke - Sex: Both - Age: All Ages (Number)                          6840 non-null   int64
 11  Deaths - Cause: All causes - Risk: Low birth weight - Sex: Both - Age: All Ages (Number)                          6840 non-null   int64
 12  Deaths - Cause: All causes - Risk: Child wasting - Sex: Both - Age: All Ages (Number)                             6840 non-null   int64
 13  Deaths - Cause: All causes - Risk: Unsafe sex - Sex: Both - Age: All Ages (Number)                                6840 non-null   int64
 14  Deaths - Cause: All causes - Risk: Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number)                6840 non-null   int64
 15  Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number)  6840 non-null   int64
 16  Deaths - Cause: All causes - Risk: Diet low in vegetables - Sex: Both - Age: All Ages (Number)                    6840 non-null   int64
 17  Deaths - Cause: All causes - Risk: Low physical activity - Sex: Both - Age: All Ages (Number)                     6840 non-null   int64
 18  Deaths - Cause: All causes - Risk: Smoking - Sex: Both - Age: All Ages (Number)                                   6840 non-null   int64
 19  Deaths - Cause: All causes - Risk: High fasting plasma glucose - Sex: Both - Age: All Ages (Number)               6840 non-null   int64
 20  Deaths - Cause: All causes - Risk: Air pollution - Sex: Both - Age: All Ages (Number)                             6840 non-null   int64
 21  Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number)                      6840 non-null   int64
 22  Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number)                         6840 non-null   int64
 23  Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number)         6840 non-null   int64
 24  Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number)                                  6840 non-null   int64
 25  Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number)                  6840 non-null   int64
 26  Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number)                      6840 non-null   int64
 27  Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number)                            6840 non-null   int64
 28  Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number)                6840 non-null   int64
 29  Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number)               6840 non-null   int64
 30  Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)                           6840 non-null   int64
dtypes: int64(29), object(2)
memory usage: 1.6+ MB

Sería recomendable cambiar el índice de las columnas ya que se trata de nombres extensos. Para ello se establece:

0 = PAIS (País)

1 = COD (Código)

2 = AÑO (Año)

3 = CAE (Contaminación aire exterior)

4 = HIP (Hipertensión)

5 = DAS (Dieta alta en sodio)

6 = DBG (Dieta baja en granos)

7 = ALC (Alcoholismo)

8 = DBF (Dieta baja en frutas)

9 = AGI (Agua insalubre)

10 = FUP (Fumador pasivo)

11 = BPN (Bajo peso al nacer)

12 = DEI (Desnutrición infantil)

13 = SXI (Sexo inseguro)

14 = DBS (Dieta baja en semillas)

15 = ACC (Aire contaminado por combustibles)

16 = DBV (Dieta baja en vegetales)

17 = BAF (Baja actividad física)

18 = TAB (Tabaquismo)

19 = GLU (Glucemia alta)

20 = CAI (Contaminación del aire)

21 = IMC (IMC alto)

22 = FSA (Falta de sanitarios)

23 = FLA (Falta de lavabos)

24 = DRO (Drogadicción)

25 = BDO (Baja densidad ósea)

26 = AVI (Avitaminosis)

27 = REC (Retraso en crecimiento)

28 = LMD (Lactancia materna discontinuada)

29 = LMN (Lactancia materna no exclusiva)

30 = DFE (Deficiencia de hierro)

In [16]:
# Cambio los índices de las columnas
data_2_v1 = data_2.rename(columns={"Entity":"PAIS","Code":"COD", "Year":"AÑO","Deaths - Cause: All causes - Risk: Outdoor air pollution - OWID - Sex: Both - Age: All Ages (Number)":"CAE","Deaths - Cause: All causes - Risk: High systolic blood pressure - Sex: Both - Age: All Ages (Number)":"HIP","Deaths - Cause: All causes - Risk: Diet high in sodium - Sex: Both - Age: All Ages (Number)":"DAS","Deaths - Cause: All causes - Risk: Diet low in whole grains - Sex: Both - Age: All Ages (Number)":"DBG","Deaths - Cause: All causes - Risk: Alcohol use - Sex: Both - Age: All Ages (Number)":"ALC","Deaths - Cause: All causes - Risk: Diet low in fruits - Sex: Both - Age: All Ages (Number)":"DBF","Deaths - Cause: All causes - Risk: Unsafe water source - Sex: Both - Age: All Ages (Number)":"AGI","Deaths - Cause: All causes - Risk: Secondhand smoke - Sex: Both - Age: All Ages (Number)":"FUP","Deaths - Cause: All causes - Risk: Low birth weight - Sex: Both - Age: All Ages (Number)":"BPN","Deaths - Cause: All causes - Risk: Child wasting - Sex: Both - Age: All Ages (Number)":"DEI","Deaths - Cause: All causes - Risk: Unsafe sex - Sex: Both - Age: All Ages (Number)":"SXI","Deaths - Cause: All causes - Risk: Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number)":"DBS","Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number)":"ACC","Deaths - Cause: All causes - Risk: Diet low in vegetables - Sex: Both - Age: All Ages (Number)":"DBV","Deaths - Cause: All causes - Risk: Low physical activity - Sex: Both - Age: All Ages (Number)":"BAF","Deaths - Cause: All causes - Risk: Smoking - Sex: Both - Age: All Ages (Number)":"TAB","Deaths - Cause: All causes - Risk: High fasting plasma glucose - Sex: Both - Age: All Ages (Number)":"GLU","Deaths - Cause: All causes - Risk: Air pollution - Sex: Both - Age: All Ages (Number)":"CAI","Deaths - Cause: All causes - Risk: High body-mass index - Sex: Both - Age: All Ages (Number)":"IMC","Deaths - Cause: All causes - Risk: Unsafe sanitation - Sex: Both - Age: All Ages (Number)":"FSA","Deaths - Cause: All causes - Risk: No access to handwashing facility - Sex: Both - Age: All Ages (Number)":"FLA","Deaths - Cause: All causes - Risk: Drug use - Sex: Both - Age: All Ages (Number)":"DRO","Deaths - Cause: All causes - Risk: Low bone mineral density - Sex: Both - Age: All Ages (Number)":"BDO","Deaths - Cause: All causes - Risk: Vitamin A deficiency - Sex: Both - Age: All Ages (Number)":"AVI","Deaths - Cause: All causes - Risk: Child stunting - Sex: Both - Age: All Ages (Number)":"REC","Deaths - Cause: All causes - Risk: Discontinued breastfeeding - Sex: Both - Age: All Ages (Number)":"LMD","Deaths - Cause: All causes - Risk: Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number)":"LMN","Deaths - Cause: All causes - Risk: Iron deficiency - Sex: Both - Age: All Ages (Number)":"DFE"})

In [17]:
# Observamos si las columnas cambiaron
data_2_v1

,PAIS,COD,AÑO,CAE,HIP,DAS,DBG,ALC,DBF,AGI,...,IMC,FSA,FLA,DRO,BDO,AVI,REC,LMD,LMN,DFE
0,Afghanistan,AFG,1990,3169,25633,1045,7077,356,3185,3702,...,9518,2798,4825,174,389,2016,7686,107,2216,564
1,Afghanistan,AFG,1991,3222,25872,1055,7149,364,3248,4309,...,9489,3254,5127,188,389,2056,7886,121,2501,611
2,Afghanistan,AFG,1992,3395,26309,1075,7297,376,3351,5356,...,9528,4042,5889,211,393,2100,8568,150,3053,700
3,Afghanistan,AFG,1993,3623,26961,1103,7499,389,3480,7152,...,9611,5392,7007,232,411,2316,9875,204,3726,773
4,Afghanistan,AFG,1994,3788,27658,1134,7698,399,3610,7192,...,9675,5418,7421,247,413,2665,11031,204,3833,812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6835,Zimbabwe,ZWE,2015,2835,11483,1063,1354,4854,1820,4336,...,5636,2879,4328,1068,407,138,730,21,734,282
6836,Zimbabwe,ZWE,2016,2781,11663,1082,1383,4915,1854,4244,...,5849,2798,4295,1042,415,101,674,20,700,275
6837,Zimbabwe,ZWE,2017,2700,11819,1098,1409,4992,1883,4193,...,6047,2744,4251,1007,424,82,629,19,678,267
6838,Zimbabwe,ZWE,2018,2669,12002,1117,1439,5044,1917,4013,...,6248,2608,4153,969,434,85,607,17,644,261
6839,Zimbabwe,ZWE,2019,2680,12241,1140,1475,5156,1960,3914,...,6475,2531,4113,963,438,81,585,16,631,259

In [18]:
# Veo los datos nulos
data_2_v1.isnull().sum().sum()

690

In [19]:
# Son 690, vemos en que columnas están
data_2_v1.isnull().sum()

PAIS      0
COD     690
AÑO       0
CAE       0
HIP       0
DAS       0
DBG       0
ALC       0
DBF       0
AGI       0
FUP       0
BPN       0
DEI       0
SXI       0
DBS       0
ACC       0
DBV       0
BAF       0
TAB       0
GLU       0
CAI       0
IMC       0
FSA       0
FLA       0
DRO       0
BDO       0
AVI       0
REC       0
LMD       0
LMN       0
DFE       0
dtype: int64

In [36]:
#Cambio los NaN por un 1
data_2_v2 = data_2_v1.fillna(1)
data_2_v2

,PAIS,COD,AÑO,CAE,HIP,DAS,DBG,ALC,DBF,AGI,...,IMC,FSA,FLA,DRO,BDO,AVI,REC,LMD,LMN,DFE
0,Afghanistan,AFG,1990,3169,25633,1045,7077,356,3185,3702,...,9518,2798,4825,174,389,2016,7686,107,2216,564
1,Afghanistan,AFG,1991,3222,25872,1055,7149,364,3248,4309,...,9489,3254,5127,188,389,2056,7886,121,2501,611
2,Afghanistan,AFG,1992,3395,26309,1075,7297,376,3351,5356,...,9528,4042,5889,211,393,2100,8568,150,3053,700
3,Afghanistan,AFG,1993,3623,26961,1103,7499,389,3480,7152,...,9611,5392,7007,232,411,2316,9875,204,3726,773
4,Afghanistan,AFG,1994,3788,27658,1134,7698,399,3610,7192,...,9675,5418,7421,247,413,2665,11031,204,3833,812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6835,Zimbabwe,ZWE,2015,2835,11483,1063,1354,4854,1820,4336,...,5636,2879,4328,1068,407,138,730,21,734,282
6836,Zimbabwe,ZWE,2016,2781,11663,1082,1383,4915,1854,4244,...,5849,2798,4295,1042,415,101,674,20,700,275
6837,Zimbabwe,ZWE,2017,2700,11819,1098,1409,4992,1883,4193,...,6047,2744,4251,1007,424,82,629,19,678,267
6838,Zimbabwe,ZWE,2018,2669,12002,1117,1439,5044,1917,4013,...,6248,2608,4153,969,434,85,607,17,644,261
6839,Zimbabwe,ZWE,2019,2680,12241,1140,1475,5156,1960,3914,...,6475,2531,4113,963,438,81,585,16,631,259

In [40]:
# Los busco por un solo año para saber que país o región tiene ese dato cambiado
data_2_v2.loc[(data_2_v2['COD']==1) & (data_2_v2['AÑO']==1990)]

,PAIS,COD,AÑO,CAE,HIP,DAS,DBG,ALC,DBF,AGI,...,IMC,FSA,FLA,DRO,BDO,AVI,REC,LMD,LMN,DFE
30,African Region (WHO),1,1990,93970,356866,46758,45763,175615,43476,809960,...,119182,604349,473096,8214,13858,101145,305355,10812,168704,18607
1620,East Asia & Pacific (WB),1,1990,792223,1973214,755103,210099,528615,297249,275997,...,387912,206690,139031,110484,56573,21453,140216,5542,113390,8918
1650,Eastern Mediterranean Region (WHO),1,1990,167123,405188,21227,102805,18994,34370,208692,...,168996,156608,83308,7917,10072,27726,95377,4342,54890,6665
1770,England,1,1990,36407,156715,9076,30295,6497,13775,6,...,52247,1,326,1381,2186,0,7,1,30,7
1950,Europe & Central Asia (WB),1,1990,622626,2384980,309584,514849,501232,193996,13647,...,941856,10934,12788,42044,53416,767,11575,660,14463,761
1980,European Region (WHO),1,1990,627103,2399430,312367,518009,502397,194493,13734,...,947836,10984,12806,42225,53617,774,11598,669,14556,763
2100,G20,1,1990,1729558,5083835,1076589,842300,1253650,608857,1174104,...,1606024,892544,519419,197175,160938,60853,331514,14476,211652,39318
3120,Latin America & Caribbean (WB),1,1990,105709,368306,54633,68240,143156,31306,94378,...,200289,61138,44000,8813,14001,3543,22351,5334,40400,2564
3690,Middle East & North Africa (WB),1,1990,140163,289453,11770,77193,9881,18177,63314,...,149018,50222,24388,4073,7935,5562,29386,2025,29199,2125
4200,North America (WB),1,1990,110408,543428,35613,112336,84305,46114,92,...,249856,93,860,26578,12258,0,43,11,211,62
4290,Northern Ireland,1,1990,828,4073,313,907,316,413,0,...,1500,0,15,45,70,0,0,0,1,0
4380,OECD Countries,1,1990,534277,2177376,250007,417407,501045,163449,20926,...,859884,12021,13446,60057,64485,1171,7556,1238,11489,791
4800,Region of the Americas (WHO),1,1990,215612,906759,89770,179421,225679,76959,94454,...,446582,61229,44756,35291,26123,3543,22392,5345,40604,2623
5130,Scotland,1,1990,2786,16385,860,3739,1532,1776,1,...,6676,0,42,203,376,0,0,0,2,1
5460,South Asia (WB),1,1990,393415,858969,103098,148046,194363,163906,1156404,...,150623,880636,489444,35592,49130,66795,308923,8258,131279,39466
5550,South-East Asia Region (WHO),1,1990,430457,1054527,183637,146673,232844,192886,1197496,...,176281,914380,493790,40431,57628,65879,305968,8046,150651,39958
5640,Sub-Saharan Africa (WB),1,1990,87226,360025,47948,45840,176589,44189,837048,...,114528,625890,489016,8193,13904,109339,320559,11243,176123,19526
6540,Wales,1,1990,2066,8753,576,2039,449,999,1,...,3125,0,20,92,163,0,0,0,1,0
6570,Western Pacific Region (WHO),1,1990,716217,1649428,663562,182241,480050,251922,116532,...,331181,88046,91519,101311,45658,8329,92297,3867,75699,4796
6630,World Bank High Income,1,1990,498579,2120532,250774,401065,484390,162736,3281,...,807304,2275,5505,60100,62934,133,1148,117,1375,284
6660,World Bank Low Income,1,1990,50472,252879,45622,32977,102584,32528,462539,...,65462,350056,288842,5268,9489,71698,199466,5854,93573,15420
6690,World Bank Lower Middle Income,1,1990,669129,1794983,251820,317172,359431,269048,1788747,...,449131,1353560,779434,53618,73227,126159,531230,18030,292971,50690
6720,World Bank Upper Middle Income,1,1990,1035573,2615825,771679,426337,692710,330957,186397,...,874761,129759,125754,116838,61600,9476,101232,9082,117235,7029

In [49]:
# Cambio el valor
dt=data_2_v2.loc[data_2_v2['PAIS']=='African Region (WHO)']
dt

,PAIS,COD,AÑO,CAE,HIP,DAS,DBG,ALC,DBF,AGI,...,IMC,FSA,FLA,DRO,BDO,AVI,REC,LMD,LMN,DFE
30,African Region (WHO),1,1990,93970,356866,46758,45763,175615,43476,809960,...,119182,604349,473096,8214,13858,101145,305355,10812,168704,18607
31,African Region (WHO),1,1991,96436,365975,47439,46897,179795,44504,829073,...,123606,618112,481775,10201,14292,100842,308125,11186,175016,18768
32,African Region (WHO),1,1992,99700,377948,48304,48317,184243,45996,819085,...,129692,610436,480386,12749,14774,99075,307088,11006,172502,19064
33,African Region (WHO),1,1993,101913,386490,48805,49393,186482,46972,815640,...,132880,607549,480444,15605,15037,97309,305786,10929,172418,19209
34,African Region (WHO),1,1994,105532,398794,49520,50736,191043,48357,832168,...,139411,619531,488628,19030,15490,96777,306251,10970,174425,19504
35,African Region (WHO),1,1995,109104,410153,50425,51970,196284,49540,824881,...,144080,614312,487466,22778,15952,95920,304929,10918,174108,19602
36,African Region (WHO),1,1996,114017,425133,51286,53584,201067,51072,826720,...,151757,615510,488745,26645,16536,95255,303220,10954,174435,19881
37,African Region (WHO),1,1997,121392,442718,52349,55350,206822,53004,823097,...,162137,612458,487913,30658,16944,93687,299937,10945,173655,20152
38,African Region (WHO),1,1998,127262,457000,53084,56769,211698,54350,818392,...,169103,608568,486683,34406,17496,91826,296218,10785,172864,20666
39,African Region (WHO),1,1999,132551,468046,53339,57997,213706,55043,809734,...,174098,601833,483707,37907,17707,90480,291485,10310,170928,21144
40,African Region (WHO),1,2000,136972,481708,53805,59359,218155,56149,796800,...,181505,591900,479228,41366,18203,86221,283959,9583,167538,21489
41,African Region (WHO),1,2001,139627,489425,53833,60225,219327,56525,784004,...,186357,582015,472903,44346,18296,81650,273801,9046,164764,21839
42,African Region (WHO),1,2002,142917,499969,54311,61420,222074,57307,765610,...,192925,567640,465451,46862,18837,75600,261790,8736,160955,22350
43,African Region (WHO),1,2003,146275,509009,54680,62421,225780,58051,743437,...,200243,550731,455518,48798,19071,70313,249699,8453,156542,22958
44,African Region (WHO),1,2004,149814,517095,55122,63376,228161,58554,722670,...,206510,534749,445813,49755,19381,64115,236324,8122,152197,23448
45,African Region (WHO),1,2005,153613,524212,55338,64120,229043,58914,706567,...,212391,522484,437709,49528,19754,57684,224840,7876,148561,23661
46,African Region (WHO),1,2006,159438,535863,56022,65207,230953,59683,704987,...,220286,520948,436745,48075,20215,48581,207394,8023,147427,23812
47,African Region (WHO),1,2007,163407,544886,56375,66020,231843,60034,691290,...,226904,510400,429564,45999,20484,43296,194505,8226,143544,23785
48,African Region (WHO),1,2008,167491,557983,57201,67325,233257,60828,674316,...,234935,497127,419803,43680,20817,41521,186570,8406,139396,23619
49,African Region (WHO),1,2009,172742,572503,58138,68825,235822,61809,661075,...,244543,486695,412293,41206,21292,38905,177462,8391,135154,23605
50,African Region (WHO),1,2010,178737,584998,58957,70191,237909,62693,642358,...,253823,471786,402566,39486,21714,37337,170537,8195,130246,23459
51,African Region (WHO),1,2011,187355,598568,60063,71952,238836,63706,621837,...,263398,455194,392044,38131,22233,36671,166824,8126,124702,23334
52,African Region (WHO),1,2012,199548,612806,61172,73759,241732,64810,602999,...,274115,439475,383718,36808,22733,33691,159330,8271,119127,22919
53,African Region (WHO),1,2013,213101,626459,62335,75276,245846,65860,588808,...,285910,427093,377753,35629,23214,30189,152038,8215,114171,22568
54,African Region (WHO),1,2014,224509,641267,63570,77009,250506,67196,575613,...,299840,415678,372356,34986,23715,27694,145518,7461,108971,22196
55,African Region (WHO),1,2015,232135,659899,65174,79616,253600,68893,560251,...,313495,402441,365090,34831,24288,24732,137929,6445,103592,21655
56,African Region (WHO),1,2016,233207,673472,66688,81402,257281,70170,549702,...,326453,393158,359264,35126,24694,22172,131262,5711,99349,21328
57,African Region (WHO),1,2017,233137,688421,68294,83575,262396,71598,541333,...,339165,385434,352197,35324,25310,19990,123831,5275,95455,21004
58,African Region (WHO),1,2018,237300,702330,70006,85857,266047,72780,513655,...,349072,364264,338328,35494,25963,19032,114354,4785,90050,20727
59,African Region (WHO),1,2019,245491,718299,71736,88234,270441,74276,492202,...,361539,347980,327473,36543,26560,18084,107069,4467,86146,20497